### ISSUE TITLE
Webstorm wrong version

### ISSUE THREAD

**Issue by altrdev** [DigiDNA/Silicon#14]
Hi, I have a mismatch for Webstom IDE.

In activity monitor:
<img width="673" alt="Screenshot 2021-04-30 at 22 57 40" src="https://user-images.githubusercontent.com/22495387/116753529-8357e280-aa07-11eb-84fe-d98b29a36a7d.png">

Silicon:
<img width="912" alt="Screenshot 2021-04-30 at 22 58 31" src="https://user-images.githubusercontent.com/22495387/116753600-9c609380-aa07-11eb-8069-089b25031265.png">

**Comment by macmade** [comment]
Thanks, I’ll look into it.

**Comment by macmade** [comment]
Which version are you using?
I just tested with the latest (version 2021.1.1 build 211.7142.46) and it is reported correctly as an universal app.

**Comment by altrdev** [comment]
same version 2021.1.1 and same build installed from Toolbox. Maybe is toolbox the problem?

**Comment by macmade** [comment]
Yes - Toolbox will install a fake "WebStorm" app, that is basically just a launcher to the full application.
The launcher is Intel only, but the real app is universal.

The one you have in Silicon is the launcher.
The one in Activity Monitor is the real app.

So both informations are correct. : )

**Comment by altrdev** [comment]
Nice!
So it's not a bug :)

**Comment by macmade** [comment]
Definitely a feature! :P
I'm closing this.
