### ISSUE TITLE
Some Apple Silicon apps are not being detected or displayed by Silicon v1.0.3

### ISSUE THREAD

**Issue by RobbieTT** [DigiDNA/Silicon#16]
Some ASi apps are missing from the Silicon display and do not feature in the 'Show All Apps' or the 'Show Apple Silicon Compatible Apps' list.  

The example below is Authy, which should feature in the last of the 'A' alphabetical list entries.  The Authy version is pure Apple Silicon (ie not Universal) and can also be run natively on iPadOS:

<img width="886" alt=" 2022-07-12 at 18 55 46" src="https://user-images.githubusercontent.com/68080817/178561384-82bcbf51-2dc1-4032-841b-6ccca231cd45.png">

<img width="377" alt=" 2022-07-12 at 18 57 17" src="https://user-images.githubusercontent.com/68080817/178561413-39deafbc-cec9-4c08-915c-22ec352db0e5.png">

My presumption is that apps that work cross-device on ASi (Mac, iOS, iPadOS) are not being detected by Silicon v1.0.3.

**Comment by macmade** [comment]
> My presumption is that apps that work cross-device on ASi (Mac, iOS, iPadOS) are not being detected by Silicon v1.0.3.

That's right. While iOS apps can run on macOS, they're not proper macOS apps.  
The bundle's structure is different, that's why they are not detected by Silicon.

I don't think it really makes sense to display them anyway, since the purpose of this app is to detect non-ARM apps.

**Comment by RobbieTT** [comment]
I'm not sure why some apps are considered proper or not, especially with the efforts made by Apple to run these apps on ASi and the general convergence of iPadOS and macOS.
Anyway, it still leaves the problem of Finder identifying Apple Apps in a different way to Silicon (UI logic fail) and that the ability to filter apps by Intel or Apple misses some Apple apps (the Apple improper apps).
May I ask that you look at this https://github.com/DigiDNA/Silicon/labels/wontfix item again?
Regards.

**Comment by macmade** [comment]
What's your exact suggestion?

**Comment by RobbieTT** [comment]
To list all Apple Silicon apps on Silicon, including those drawn from other ASi operating systems, as per the reference target of the Finder UI.  
As a stretch target (and very much optional feature enhancement) to add a further discriminator to Silicon to identify the original / native OS (iPadOS, iOS etc) of these cross-platform apps.

**Comment by macmade** [comment]
I'll look into it : )

**Comment by macmade** [comment]
Should be fixed in 434f696bda004c8207e3f639f1461b7314d5c304.

Here's a test build: can you check that everything's OK on your side?
[Silicon.app.zip](https://github.com/DigiDNA/Silicon/files/9151535/Silicon.app.zip)

**Comment by RobbieTT** [comment]
Test build loads and runs without error.  Correctly distinguishes between all Apple Silicon (macOS), Apple Silicon (iOS family), Universal and Intel-only apps:

<img width="912" alt=" 2022-07-20 at 16 39 40" src="https://user-images.githubusercontent.com/68080817/180025207-c67d4444-82fd-4886-9471-6b204d85fc1d.png">

Good arrows, Sir.  👍

**Comment by RobbieTT** [comment]
This issue can be closed - issue resolved.
