### ISSUE TITLE
Swift 4 version?

### ISSUE THREAD

**Issue by Janne-M** [DigiDNA/Silicon#19]
Current project is in Swift 3 and is not supported in current versions of Xcode. And it demands Xcode 10.1 do convert and that will not run on modern OS's. It's hard to contribute when we can't open the project...

**Comment by macmade** [comment]
Project is written in Swift 5 and is compatible with latest Xcode versions.  
You probably forgot to clone including submodules:

    git submodule update --init --recursive

This will fix the issue.

**Comment by Janne-M** [comment]
Great! To confess I actually just downloaded the zip-file...
