### ISSUE TITLE
Support for 10.14.6?

### ISSUE THREAD

**Issue by dasmurphy** [DigiDNA/Silicon#2]
Would it be possible to support the older 10.14.6 OS too? Since i don't have 10.15 (yet)?

Thanks for any answer.

**Comment by macmade** [comment]
Thanks for the request. Probably, I’ll check this as soon as possible and publish an update if everything’s fine on 10.14.

**Comment by macmade** [comment]
The app runs fine on 10.14, so I lowered the deployment target.  
An update should be available in a few hours.

**Comment by dasmurphy** [comment]
Thanks for the very fast response. Awesome.
