### ISSUE TITLE
[feature suggestion] re-scan button

### ISSUE THREAD

**Issue by sanberkzulfikar** [DigiDNA/Silicon#20]
A re-scan button would be nice.

**Comment by macmade** [comment]
Just hit command-n 😉

**Comment by sanberkzulfikar** [comment]
Appreciated the alternative solution but how about the feature?

**Comment by macmade** [comment]
What do you mean? Command-n does exactly that…

**Comment by sanberkzulfikar** [comment]
I didn't say it's not working. Read my first message, see the button feature suggestion. You are interesting.

**Comment by macmade** [comment]
I think command-n is a pretty well known system-wide shortcut.
I don’t really want to create buttons for every item in the app’s menu bar.
