### ISSUE TITLE
Default to "Show Intel-only app" ?

### ISSUE THREAD

**Issue by mrleblanc101** [DigiDNA/Silicon#22]
Shouldn't this filter be the default ?
I always activate this filter everytime I open the app.

**Comment by macmade** [comment]
I can make these settings persistent.

**Comment by mrleblanc101** [comment]
That would be great

**Comment by macmade** [comment]
Version 1.0.5 is now available: https://github.com/DigiDNA/Silicon/releases/tag/1.0.5

**Comment by mrleblanc101** [comment]
Works great ! Thanks
