### ISSUE TITLE
Incorrect detection

### ISSUE THREAD

**Issue by Mike-Junmin** [DigiDNA/Silicon#24]
PyCharm Professional edition and IntelliJ IDEA Ultimate, downloaded via jetbrain toolbox, are both detected as Intel 64 in the app where the activity monitor app shows their kind to be Apple. The jetbrain toolbox app is correctly detected as Apple.

**Comment by macmade** [comment]
The apps installed by the JetBrain toolbox in `~/Applications/` are not the real apps, but just launchers.  
And they are indeed intel only.

    lipo -info ~/Applications/JetBrains\ Toolbox/IntelliJ\ IDEA\ Ultimate.app/Contents/MacOS/jetbrains-toolbox-launcher
    
    Non-fat file: ~/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app/Contents/MacOS/jetbrains-toolbox-launcher is architecture: x86_64

The real apps are located in `~/Library/Application Support/JetBrains/Toolbox/apps`
