### ISSUE TITLE
Empty window appears on launch on macOS Sequoia

### ISSUE THREAD

**Issue by brokosz** [DigiDNA/Silicon#28]
There's an empty window that appears on launch for macOS 15 and later.

**Comment by macmade** [comment]
I cannot reproduce it using the latest version (1.0.5-68) on macOS Sequoia 15.0.1.

Which version of Silicon and macOS are you using?

**Comment by brokosz** [comment]
sorry - closing this. I was looking at the wrong cask. This should have been for Silicon Info.

**Comment by brokosz** [comment]
sorry - closing this. I was looking at the wrong cask. This should have been for Silicon Info.
