### ISSUE TITLE
Exclude "Apple Apps" Feature

### ISSUE THREAD

**Issue by dasmurphy** [DigiDNA/Silicon#5]
Here is a feature request. How about an option to exclude all Apple Own Apps like `Preview` or `App Store`?

May be it can also include `Sparkle` exclusion too. Or Apps within Apps.

I think should be possible without problem when scanning the plist i think.

**Comment by macmade** [comment]
Apps within apps are not scanned by default, but this can be changed using the "Recurse into Applications" checkbox.

I'll add an option for excluding apps from Apple.

**Comment by macmade** [comment]
This has been implemented in 1.0.2: https://github.com/DigiDNA/Silicon/releases/tag/1.0.2
