### ISSUE TITLE
Tweetbot 3.5 is not recognized as a valid application

### ISSUE THREAD

**Issue by rtwld** [DigiDNA/Silicon#6]
The latest [Tweetbot](https://tapbots.com/tweetbot/mac/) version 3.5 for macOS (I am using the trial version) is now universal, but is not recognized as an application by Silicon. 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/7947266/100285823-d8339080-2f71-11eb-8b27-0a2f184e346f.png">

The app is recognized in `System information → Software → Applications` just fine

<img width="616" alt="image" src="https://user-images.githubusercontent.com/7947266/100286022-5001bb00-2f72-11eb-82c9-c5f32071b3f7.png">

**Comment by macmade** [comment]
Thanks for reporting this.  
I was not handling renamed apps correctly - This has been fixed in 04f45bd9ec4c16647299b6c285ee6045013a552f.

I'll publish an update probably tomorrow, as I also want to address #5.

**Comment by macmade** [comment]
Version 1.0.2 is now available: https://github.com/DigiDNA/Silicon/releases/tag/1.0.2
